//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Player: [
      { Name: 'Name 1', Age: 1, Wins: 1, Email: 'Email 1', id: 21 },
      { Name: 'Name 2', Age: 2, Wins: 2, Email: 'Email 2', id: 51 },
      { Name: 'Name 3', Age: 3, Wins: 3, Email: 'Email 3', id: 53 },
      { Name: 'Name 4', Age: 4, Wins: 4, Email: 'Email 4', id: 24 },
      { Name: 'Name 5', Age: 5, Wins: 5, Email: 'Email 5', id: 34 },
    ],
  },
};
export default data;
