//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Player: {
      name: 'Player',
      fields: {
        Name: 'Name',
        Age: 'Age',
        Wins: 'Wins',
        Email: 'Email',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Player: {
      name: 'Player (fr)',
      fields: {
        Name: 'Name (fr)',
        Age: 'Age (fr)',
        Wins: 'Wins (fr)',
        Email: 'Email (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
